from pyChatGPT import ChatGPT


print("Welcome to ChatGPT Python Assistant V1.0.")
print("1-Google")
print("2-Microsoft")
print("3-Section Token ID(Required to note in code section)")
logging=input("Please choose a login option above in order to be able to use the assistant.(Just write the number.):")
global api

if logging=='1':  # auth with google login
    a=input("E-mail:")
    b=input("Password:")
    print("Please wait while the assistant preparing.")
    api = ChatGPT(auth_type='google', email=a, password=b)
    
    

elif logging=='2': # auth with microsoft login
    a=input("E-mail:")
    b=input("Password:")
    print("Please wait while the assistant preparing..")
    api = ChatGPT(auth_type='microsoft', email=a, password=b)
    
   

elif logging=='3': # auth with session token (`__Secure-next-auth.session-token` cookie from https://chat.openai.com/chat)
    
    session_token = input('Write your session token here.')
    api = ChatGPT(session_token)
   
else:
    print("Error:Wrong Input. Quitting from the program.")
    temp=input("Enter something:")
    raise SystemExit
    
    
while True:
    ask=input("Ask anything(Q to exit):")
    if ask=='Q': 
        api.reset_conversation()    # reset the conversation.
        break
    resp = api.send_message(ask)
    print('Answer:', resp['message'])


'''
Other logging options are below.
# auth with openai login (captcha solving using speech-to-text engine)
api = ChatGPT(auth_type='openai', email='example@gmail.com', password='password')
# auth with openai login (manual captcha solving)
api = ChatGPT(
    auth_type='openai', captcha_solver=None,
    email='example@gmail.com', password='password'
)

# auth with openai login (2captcha for captcha solving)
api = ChatGPT(
    auth_type='openai', captcha_solver='2captcha', solver_apikey='abc',
    email='example@gmail.com', password='password'
)
# reuse cookies generated by successful login before login,
# if `login_cookies_path` does not exist, it will process logining  with `auth_type`, and save cookies to `login_cookies_path`
# only works when `auth_type` is `openai` or `google`
api = ChatGPT(auth_type='openai', email='example@xxx.com', password='password',
    login_cookies_path='your_cookies_path',
)
'''

'''
These options below are optional.
api = ChatGPT(session_token, conversation_id='some-random-uuid')  # specify conversation id 

api = ChatGPT(session_token, proxy='https://proxy.example.com:8080')  # specify proxy
api = ChatGPT(session_token, chrome_args=['--window-size=1920,768'])  # specify chrome args
api = ChatGPT(session_token, moderation=False)  # disable moderation
api = ChatGPT(session_token, verbose=True)  # verbose mode (print debug messages)


api.clear_conversations()  # Clear all conversations.
api.refresh_chat_page()    # Refresh the chat page.
'''
